### ISSUE TITLE
After phone call watch does not come out of DND

### ISSUE THREAD

**Issue by timkgh** [blunden/DoNotDisturbSync#1]
Nexus 6P, Huawei watch 1st gen. At the start of a phone call, the phone app puts the phone in DND mode and the watch also goes into DND mode (I have the 2-way sync enabled via adb). At the end of the phone call the phone comes out of DND mode but most of the time the watch remains in DND, so the sync phone -> watch does not always work.

**Comment by blunden** [comment]
Can you provide logcat logs (with timestamps) from both the watch and phone when this happens?

**Comment by blunden** [comment]
Should be fixed in the upcoming 1.4 release.
