### ISSUE TITLE
App missing in Wear OS 2.6

### ISSUE THREAD

**Issue by drodil** [blunden/DoNotDisturbSync#5]
Recently updated my watch to Wear OS 2.6 and the app is no longer in the list. Google Play shows it still as installed though. Also it's not syncing anymore. This is a great little piece of software but unfortunately seems like broken in newer versions.

**Comment by darren3** [comment]
It's not working for me either on Wear OS 2.8, I have the same problems listed above.

**Comment by blunden** [comment]
Yes, it was removed from the Play Store because it uses legacy APIs.

See my response linked below for how to make it work on newer Wear OS versions before a new version is published.
https://github.com/blunden/DoNotDisturbSync/issues/6#issuecomment-1012545839
