### ISSUE TITLE
Phone-to-Watch not working

### ISSUE THREAD

**Issue by cashpw** [blunden/DoNotDisturbSync#6]
I have installed Do Not Disturb Sync for Wear version 1.3 on my phone (Pixel 4 XL) and have installed the related app on my watch as well. Watch-to-phone DND sync is working as expected. I can enable DND on my watch and see that it is automatically enabled on my phone.

Phone-to-watch, unfortunately, is not working. I have followed the instructions in the [README](https://github.com/blunden/DoNotDisturbSync/blob/master/README.md) to no avail. I was able to successfully set the `enable_notification_listeners` setting and read the setting back out :

```sh
$ adb connect 192.168.1.XXX

$ adb shell

triggerfish:/ $ settings put secure enabled_notification_listeners com.google.android.wearable.app/com.google.android.clockwork.stream.NotificationCollectorService:se.blunden.donotdisturbsync/se.blunden.donotdisturbsync.DummyNotificationListener

triggerfish:/ $ settings get secure enabled_notification_listeners
com.google.android.wearable.app/com.google.android.clockwork.stream.NotificationCollectorService:se.blunden.donotdisturbsync/se.blunden.donotdisturbsync.DummyNotificationListener
```

After entering these commands, phone-to-watch DND sync is not working. Additionally, after enabling DND on my watch, the `enabled_notification_listeners` setting seems to reset:

```
triggerfish:/ $ settings get secure enabled_notification_listeners
com.google.android.wearable.app/com.google.android.clockwork.stream.NotificationCollectorService:se.blunden.donotdisturbsync/se.blunden.donotdisturbsync.DummyNotificationListener

<I enable DND on my watch>

triggerfish:/ $ settings get secure enabled_notification_listeners
com.google.android.wearable.app/com.google.android.clockwork.stream.NotificationCollectorService
```

**Comment by Jefferderp** [comment]
Same issue, reproduced identically as described.

Watch reports "Wear OS by Google" version 2.17 (May 2020 security patch).

**Comment by socram70** [comment]
Same here with Android 11 (Pixel 5)

**Comment by blunden** [comment]
See the updated instructions for Wear OS. The new command works on Wear OS 3.0, and hopefully Wear OS 2.x as well. Requires sideloading the watch component (watch.apk available under releases) to the watch via ADB (adb install watch.apk) beforehand.
